name: CI-release

on:
  push:
    tags:
      - "v[0-9]+"

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Release Version
        id: extract_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      - name: Get Repository Owner
        id: get_owner
        run: echo "::set-output name=owner::$(echo ${{ github.repository }} | cut -d '/' -f 1)"

      - name: Install dependencies
        run: npm ci

      # - uses: fregante/release-with-changelog@v3
      #   with:
      #     token: ${{ secrets.MY_TOKEN }}

      - name: Create Release Issue
        run: npm run create:issue
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_OWNER: ${{ steps.get_owner.outputs.owner }}
