name: CI-release

on:
  push:
    tags:
      - "v[0-9]+"

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        run: |
          previous_tag=$(git tag --sort=-creatordate | sed -n '2p')
          changelog=$(git log --pretty=format:"- %s" "$previous_tag".."$GITHUB_REF")

          echo "Current tag: $GITHUB_REF"
          echo "Previous tag: ${previous_tag}"

          echo "::set-output name=version::${{ github.ref#refs/tags/v }}"
          echo "::set-output name=changelog::${changelog}"

      - name: ✍️ Create release issue
        uses: imjohnbo/issue-bot@3d96848fb5e9a4a473bb81ae62b4b4866a56e93a
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          assignees: "DaniilOkrug"
          labels: "RELEASE"
          title: Release ${{ steps.changelog.outputs.version }}
          body: |
            ### Релиз ${{ steps.changelog.outputs.version }}

            Авто: ${{ github.actor }}

            Время: ${{ steps.get_tags.outputs.timestamp }}

            Changelog:

            ${{ ssteps.changelog.outputs.changelog }}

            Для запуска развертывания перейдите на страницу экшена и выберите ветку релиза

          pinned: false
          close-previous: false
