name: CI-release

on:
  push:
    tags:
      - "v[0-9]+"

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Release Version
        id: extract_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      - name: Generate Changelog
        id: changelog
        run: |
          previous_tag=$(git tag --sort=-creatordate | sed -n '2p')
          echo ${{previous_tag}}

          changelog=$(git log --pretty=format:"- %s" "$previous_tag".."$GITHUB_REF")
          echo "::set-output name=changelog::${changelog}"

      - name: Create/Update Release Issue
        id: create_update_issue
        run: |
          issue_title="Release v${{ steps.extract_version.outputs.version }}"
          issue_body="Version: v${{ steps.extract_version.outputs.version }}\nChangelog:\n${{ steps.changelog.outputs.changelog }}"
          release_issue_number=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues?state=all" | jq -r '.[] | select(.title=="'"$issue_title"'") | .number')
          if [[ -z "$release_issue_number" ]]; then
            curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d "{\"title\":\"$issue_title\",\"body\":\"$issue_body\"}" "https://api.github.com/repos/${{ github.repository }}/issues"
          else
            curl -s -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d "{\"body\":\"$issue_body\"}" "https://api.github.com/repos/${{ github.repository }}/issues/$release_issue_number"
          fi

      - name: Close Release Issue
        if: ${{ github.event_name == 'push' }}
        run: |
          issue_title="Release v${{ steps.extract_version.outputs.version }}"
          issue_number=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues?state=all" | jq -r '.[] | select(.title=="'"$issue_title"'") | .number')
          if [[ -n "$issue_number" ]]; then
            curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d "{\"state\":\"closed\"}" "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number"
          fi
