name: CI-release

on:
  push:
    tags:
      - "v[0-9]+"

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      # - uses: fregante/release-with-changelog@v3
      #   with:
      #     token: ${{ secrets.MY_TOKEN }}

      - name: Create Release Issue
        run: npm start
        with:
          token: ${{ secrets.MY_TOKEN }}
          action-id: ${{ github.run_id }}
          owner: "Daniil Okrug"
