name: CI-release

on:
  push:
    tags:
      - "v[0-9]+"

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        run: |
          previous_tag=$(git tag --sort=-creatordate | sed -n '2p')
          changelog=$(git log --pretty=format:"- %s" "$previous_tag".."$GITHUB_REF")

          echo "Current tag: $GITHUB_REF"
          echo "Previous tag: ${previous_tag}"

          echo "::set-output name=changelog::${changelog}"

      # - name: ✍️ Create release issue
      #   uses: imjohnbo/issue-bot@3d96848fb5e9a4a473bb81ae62b4b4866a56e93a
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      #   with:
      #     assignees: "sr480"
      #     labels: "RELEASE"
      #     title: Release ${{ github.ref_name }}
      #     body: |
      #       ### Это релиз приложения версии ${{ github.ref_name }}

      #       Авто релиза: ${{ github.actor }}

      #       Время: ${{ steps.get_tags.outputs.timestamp }}

      #       Changelog:

      #       ${{ steps.generate_log.outputs.log }}

      #       Для запуска развертывания перейдите на страницу экшена и выберите ветку релиза

      #       [Deploy application](https://github.com/sr480/unit-demo-cra/actions/workflows/build-deploy-github-actions.yml)

      #     pinned: false
      #     close-previous: false
